#!/system/bin/sh

#modmanager disable diy_glasses enable_debug_menu
#we use dinit instead as this makes it configurator friendly out of the box
/opt/sbin/dinitctl -u disable tweak-enable-debug-menu || true
